package modelos;
// Generated 28/07/2022 03:06:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Continente generated by hbm2java
 */
public class Continente  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set paises = new HashSet(0);

    public Continente() {
    }

	
    public Continente(String nombre) {
        this.nombre = nombre;
    }
    public Continente(String nombre, Set paises) {
       this.nombre = nombre;
       this.paises = paises;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getPaises() {
        return this.paises;
    }
    
    public void setPaises(Set paises) {
        this.paises = paises;
    }




}


